version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: .devcontainer/Dockerfile
    # entrypoint: /bin/sh -c "while sleep 1000; do :; done"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace:cached
    ports:
      - 8080:8080
      - 5005:5005
    networks:
        - backend_mysql
    depends_on:
      - mysql
 
    
  